// This is generated by writeCoreProposal; please edit!
/* eslint-disable */

const manifestBundleRef = {bundleID:"b1-938304530ab413804ba64aa99a73cccb6f2068c285631463f5bd7e6e42dda81bc27fc81a6976ab7907d19d5d0e31ee5a1eaa05bc7234c7d102cc0a0f3a34ff60"};
const getManifestCall = harden([
  "getManifestForAddAssetToVault",
  {
    debtLimitValue: undefined,
    interchainAssetOptions: {
      decimalPlaces: 6,
      denom:
        "ibc/49C630713B2AB60653F76C0C58D43C2A64956803B4D422CACB6DD4AD016ED846",
      initialPrice: undefined,
      issuerBoardId: undefined,
      keyword: "STATOM",
      oracleBrand: "STATOM",
      proposedName: "stATOM",
    },
    interestRateValue: undefined,
    scaledPriceAuthorityRef: {
      bundleID: "b1-e4ba9cb60b5b59d4d4618710991fe8a503dd4a07c7f17029a342ccb41893bc961ae63bcb0e2c20e4bc2415c9755f090f7761751cdd00b85762902b357a48c5cf",
    },
  },
]);
const overrideManifest = {
  addAssetToVault: {
    brand: {
      consume: {
        IST: true,
      },
    },
    consume: {
      agoricNamesAdmin: true,
      auctioneerKit: "auctioneer",
      vaultFactoryKit: "vaultFactory",
    },
    instance: {
      consume: true,
    },
  },
  publishInterchainAssetFromBank: {
    consume: {
      agoricNamesAdmin: true,
      bankManager: true,
      bankMints: true,
      reserveKit: true,
      startUpgradable: true,
      vBankKits: true,
    },
    installation: {
      consume: {
        mintHolder: true,
      },
    },
    produce: {
      bankMints: true,
      vBankKits: true,
    },
  },
  registerScaledPriceAuthority: {
    consume: {
      agoricNamesAdmin: true,
      priceAuthority: true,
      priceAuthorityAdmin: true,
      scaledPriceAuthorityKits: true,
      startUpgradable: true,
    },
    installation: {
      consume: {
        scaledPriceAuthority: true,
      },
    },
    produce: {
      scaledPriceAuthorityKits: true,
    },
  },
};

// Make the behavior the completion value.
(({
  manifestBundleRef,
  getManifestCall,
  overrideManifest,
  E,
  log = console.info,
  restoreRef: overrideRestoreRef,
}) => {
  const { entries, fromEntries } = Object;

  // deeplyFulfilled is a bit overkill for what we need.
  const shallowlyFulfilled = async obj => {
    if (!obj) {
      return obj;
    }
    const ents = await Promise.all(
      entries(obj).map(async ([key, valueP]) => {
        const value = await valueP;
        return [key, value];
      }),
    );
    return fromEntries(ents);
  };

  /** @param {ChainBootstrapSpace & BootstrapPowers & { evaluateBundleCap: any }} allPowers */
  const behavior = async allPowers => {
    // NOTE: If updating any of these names extracted from `allPowers`, you must
    // change `permits` above to reflect their accessibility.
    const {
      consume: { vatAdminSvc, zoe, agoricNamesAdmin },
      evaluateBundleCap,
      installation: { produce: produceInstallations },
      modules: {
        utils: { runModuleBehaviors },
      },
    } = allPowers;
    const [exportedGetManifest, ...manifestArgs] = getManifestCall;

    /** @type {(ref: import\('./externalTypes.js').ManifestBundleRef) => Promise<Installation<unknown>>} */
    const defaultRestoreRef = async ref => {
      // extract-proposal.js creates these records, and bundleName is
      // the name under which the bundle was installed into
      // config.bundles
      const p =
        'bundleName' in ref
          ? E(vatAdminSvc).getBundleIDByName(ref.bundleName)
          : ref.bundleID;
      const bundleID = await p;
      const label = bundleID.slice(0, 8);
      return E(zoe).installBundleID(bundleID, label);
    };
    const restoreRef = overrideRestoreRef || defaultRestoreRef;

    // Get the on-chain installation containing the manifest and behaviors.
    console.info('evaluateBundleCap', {
      manifestBundleRef,
      exportedGetManifest,
      vatAdminSvc,
    });
    let bcapP;
    if ('bundleName' in manifestBundleRef) {
      bcapP = E(vatAdminSvc).getNamedBundleCap(manifestBundleRef.bundleName);
    } else {
      bcapP = E(vatAdminSvc).getBundleCap(manifestBundleRef.bundleID);
    }
    const bundleCap = await bcapP;

    const manifestNS = await evaluateBundleCap(bundleCap);

    console.error('execute', {
      exportedGetManifest,
      behaviors: Object.keys(manifestNS),
    });
    const {
      manifest,
      options: rawOptions,
      installations: rawInstallations,
    } = await manifestNS[exportedGetManifest](
      harden({ restoreRef }),
      ...manifestArgs,
    );

    // Await references in the options or installations.
    const [options, installations] = await Promise.all(
      [rawOptions, rawInstallations].map(shallowlyFulfilled),
    );

    // Publish the installations for behavior dependencies.
    const installAdmin = E(agoricNamesAdmin).lookupAdmin('installation');
    await Promise.all(
      entries(installations || {}).map(([key, value]) => {
        produceInstallations[key].resolve(value);
        return E(installAdmin).update(key, value);
      }),
    );

    // Evaluate the manifest for our behaviors.
    return runModuleBehaviors({
      allPowers,
      behaviors: manifestNS,
      manifest: overrideManifest || manifest,
      makeConfig: (name, _permit) => {
        log('coreProposal:', name);
        return { options };
      },
    });
  };

  // Make the behavior the completion value.
  return behavior;
})({ manifestBundleRef, getManifestCall, overrideManifest, E });
